### ISSUE TITLE
Много именованных областей

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#10]
Лучше создать отдельный блок с общей именованной областью - внутри нее уже сделать свой флексбок или грид, смотря что удобней
https://github.com/Uliana-Redfeather/ITgirls-homework/blob/8f7321d453a70dba68286af7dcccc749f33f604a/weeek-7/style1.css#L61

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/404544f7d4d4600c49f32101e01b789d4ef31a63
