### ISSUE TITLE
Не используй тег br

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#11]
Вместо тега br тебе на помощь могут прийти отступы)
+флексбоксы и другие варианты)
https://github.com/Uliana-Redfeather/ITgirls-homework/blob/8f7321d453a70dba68286af7dcccc749f33f604a/weeek-7/project.html#L51

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/404544f7d4d4600c49f32101e01b789d4ef31a63
