### ISSUE TITLE
названия классов

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#12]
Чем по смыслу отличаются классы header-2, header-1 - лучше выбирать более осмысленные названия)

Попробуй переименовать классы с учетом БЭМ
https://ru.bem.info/methodology/quick-start/

https://github.com/Uliana-Redfeather/ITgirls-homework/blob/8f7321d453a70dba68286af7dcccc749f33f604a/weeek-7/project.html#L15

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/404544f7d4d4600c49f32101e01b789d4ef31a63
