### ISSUE TITLE
Много тегов header

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#13]
header - обозначает область на сайте, где размещается шапка сайта, таких областей не должно быть много

Создай один header, в него положи все нужные заголовки

https://developer.mozilla.org/ru/docs/Web/HTML/Element/header

https://github.com/Uliana-Redfeather/ITgirls-homework/blob/8f7321d453a70dba68286af7dcccc749f33f604a/weeek-7/project.html#L16

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/404544f7d4d4600c49f32101e01b789d4ef31a63
