### ISSUE TITLE
Вместо id - классы

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#3]
В верстке широко распространено использование классов, а не id для указания стилей - поправь, пожалуйста, айди на классы:) 
https://github.com/Uliana-Redfeather/ITgirls-homework/blob/2fe4507c540d32025896171ab6db2226bf8113eb/portfolio.html#L9

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/f38772223d3f04a6af94fc5f1c766592886cf1bd
