### ISSUE TITLE
Лишний div

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#4]
Старайся использовать как можно меньше лишних тегов 

https://github.com/Uliana-Redfeather/ITgirls-homework/blob/2fe4507c540d32025896171ab6db2226bf8113eb/index6.html#L68

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/f38772223d3f04a6af94fc5f1c766592886cf1bd
