### ISSUE TITLE
Создание единого футера

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#5]
Чтобы не создавать много однотипных классов, можно создать один контейнер footer - разместить его на последней строке, а внутри него добавить еще 4 элемента (то есть сделать футер контейнером грид или флекс)
https://github.com/Uliana-Redfeather/ITgirls-homework/blob/a8e049eb8a94d977edb9d25e059a0ca50a38e909/week-6/style.css#L66

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/25cd1fdf1ebc26120244b03747dc255a9b9b0416
