### ISSUE TITLE
Форматирование файлов

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#6]
Этот комментарий актуален для всех файлов - их нужно форматировать, чтобы код смотрелся красиво)
В VS Code нажимаем правой кнопкой мышки по коду - форматировать - выбираем с помощью prettier :)

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/25cd1fdf1ebc26120244b03747dc255a9b9b0416
