### ISSUE TITLE
Более красноречивые названия классов

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#7]
Придумывать названия классам бывает непросто, но постарайся подобрать для них что-то более красноречивое)
Может dicrease-rate-advantages (dicrease-rate-advantages-text)
https://github.com/Uliana-Redfeather/ITgirls-homework/blob/a8e049eb8a94d977edb9d25e059a0ca50a38e909/week-6/style1.css#L12

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/82d14c75e7ab70e5fafd5575314981158ed43d33
