### ISSUE TITLE
Фиксированные значения по высоте и ширине

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#8]
Старайся не использовать фиксированные значения по ширине и высоте - при просмотра с телефона или планшета могут возникать проблемы - лучше задавать минимальные и максимальные значения и через контейнер с помощью флекс или грид группировать элементы, в процентах указывая ширину :)
https://github.com/Uliana-Redfeather/ITgirls-homework/blob/a8e049eb8a94d977edb9d25e059a0ca50a38e909/week-6/style1.css#L25

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/82d14c75e7ab70e5fafd5575314981158ed43d33
