### ISSUE TITLE
Футер убирается

### ISSUE THREAD

**Issue by itgirlschool** [Uliana-Redfeather/ITgirls-homework#9]
Почему футер прячется на маленьких экранах - как расположить его, чтобы он красиво смотрелся?
Например, в столбик
https://github.com/Uliana-Redfeather/ITgirls-homework/blob/8f7321d453a70dba68286af7dcccc749f33f604a/weeek-7/style1.css#L94

**Comment by Uliana-Redfeather** [comment]
https://github.com/Uliana-Redfeather/ITgirls-homework/commit/404544f7d4d4600c49f32101e01b789d4ef31a63
